/* eslint-disable @next/next/no-img-element -- Game and player artwork is served from the game APIs. */
"use client";

import { useState } from "react";
import type { DesktopAdvice, DesktopMatch, DesktopStatus } from "./desktop";
import type { StatlockerProfile } from "./lib/data/statlocker";
import { playerRank } from "./lib/player-rank";
import { scoreThreats } from "./lib/build-engine/threat-score";
import { buildStageAt, purchaseState } from "./lib/build-engine/presentation";

type Hero = { id: number; name: string; images?: { icon_image_small_webp?: string } };
type Item = { id: number; name: string; cost: number | null; item_slot_type: string | null; shop_image_webp?: string };
type Entry = { item: Item & { item_tier?: number | null }; enemyRates: Array<{ heroId: number; lift: number }>; threatTargets?: number[]; coveredEnemyIds?: number[]; teamBuyTime: number; carryBuyTime: number; teamRate: number; carryRate: number; baselineRate: number; teamMatches: number; carryMatches: number; teamScore?: number; carryScore?: number; mechanicFit?: number; counterUrgency?: number; personalFit?: number; exactFit?: number };
type Plan = { early: Entry[]; mid: Entry[]; late: Entry[]; weapon: Entry[]; vitality: Entry[]; spirit: Entry[]; flex: Entry[]; purchaseOrder: Entry[]; corePath: Entry[]; adaptiveCounters: Entry[]; situational: Entry[]; normalCoreNextId: number | null; nextBuyOrder: Array<{ itemId: number; nextBuyScore: number; deviationCost?: number }>; sellSuggestions: Array<{ sell: Entry; replacement: Entry; reason?: string }> };

export function DesktopBuildLab({ status, match, heroes, items, profiles, lang, plan, cost, remainingCost, ownedItemIds, liveOwnedItemIds, onToggleOwned, onSave, onLoad, presetMessage, buyTarget, advice, recommendations }: {
  status: DesktopStatus; match: DesktopMatch | null; heroes: Map<number, Hero>; items: Item[]; profiles: Record<number, StatlockerProfile>; lang: "en" | "de"; plan: Plan; cost: number; remainingCost: number; ownedItemIds: number[]; liveOwnedItemIds: number[]; onToggleOwned: (id: number) => void; onSave: () => void; onLoad: () => void; presetMessage: string | null; buyTarget: "team" | "carry"; advice: DesktopAdvice | null; recommendations: Entry[];
}) {
  const de = lang === "de", locale = de ? "de-DE" : "en-US";
  const [selectedEnemy, setSelectedEnemy] = useState<number | null>(null);
  const [groupFilter, setGroupFilter] = useState<"all" | "core" | "counter" | "situational">("all");
  const live = status.in_game && !!match;
  const own = live ? match.players.find((player) => player.account_id != null && player.account_id === match.account_id) : null;
  const enemies = own?.team == null ? [] : match!.players.filter((player) => player.team != null && player.team !== own.team && player.hero_id != null);
  const rankedThreats = scoreThreats(enemies.map((player) => ({ heroId: player.hero_id!, netWorth: player.net_worth, soulsPerMinute: match?.game_time_s && player.net_worth != null ? player.net_worth / Math.max(1, match.game_time_s / 60) : null, kills: player.kills, deaths: player.deaths, assists: player.assists })), match?.game_time_s ?? null);
  const owned = new Set(ownedItemIds), liveOwned = new Set(liveOwnedItemIds), itemById = new Map(items.map((item) => [item.id, item]));
  const candidates = plan.purchaseOrder.filter((entry) => !owned.has(entry.item.id));
  const current = live && own?.hero_id != null && enemies.length > 0
    ? candidates.find((entry) => entry.item.id === advice?.recommended?.item_id) ?? recommendations.find((entry) => entry.item.id === advice?.recommended?.item_id) ?? candidates[0] ?? null
    : null;
  const normalCore = plan.purchaseOrder.find((entry) => entry.item.id === plan.normalCoreNextId) ?? recommendations.find((entry) => entry.item.id === plan.normalCoreNextId);
  const detailCurrent = current ? recommendations.find((entry) => entry.item.id === current.item.id) ?? current : null;
  const targetIds = current?.threatTargets?.length ? current.threatTargets : current?.enemyRates.map((row) => row.heroId) ?? [];
  const targetPlayer = (selectedEnemy == null ? undefined : enemies.find((player) => player.hero_id === selectedEnemy)) ?? targetIds.map((id) => enemies.find((player) => player.hero_id === id)).find(Boolean);
  const targetProfile = targetPlayer?.account_id == null ? undefined : profiles[targetPlayer.account_id];
  const ownProfile = own?.account_id == null ? undefined : profiles[own.account_id];
  const currentCost = current?.item.cost ?? null, souls = own?.unspent_souls ?? null;
  const purchase = purchaseState(currentCost, souls);
  const affordability = purchase.status === "unknown" ? (de ? "SEELEN UNBEKANNT" : "SOULS UNKNOWN") : purchase.status === "buy" ? (de ? "JETZT KAUFEN" : "BUY NOW") : `${de ? "SPARE" : "SAVE"} ${purchase.shortfall.toLocaleString(locale)}`;
  const deviation = current ? plan.nextBuyOrder.find((entry) => entry.itemId === current.item.id)?.deviationCost ?? 0 : 0;
  const inventory = { weapon: [] as Item[], vitality: [] as Item[], spirit: [] as Item[] };
  ownedItemIds.forEach((id) => { const item = itemById.get(id); if (item?.item_slot_type === "weapon" || item?.item_slot_type === "vitality" || item?.item_slot_type === "spirit") inventory[item.item_slot_type].push(item); });
  const flex = (Object.values(inventory) as Item[][]).flatMap((group) => group.slice(4)).slice(0, 4);
  const icon = (id: number) => { const url = itemById.get(id)?.shop_image_webp ?? recommendations.find((entry) => entry.item.id === id)?.item.shop_image_webp; return url ? <img src={url} alt="" /> : <span aria-hidden="true">◆</span>; };
  const itemTargetIds = (entry: Entry) => entry.threatTargets?.length ? entry.threatTargets : entry.coveredEnemyIds?.length ? entry.coveredEnemyIds : entry.enemyRates.map((row) => row.heroId);
  const onCorePath = !!current && current.item.id === plan.normalCoreNextId;
  const stage = buildStageAt(match?.game_time_s);
  const groups = [
    { id: "core" as const, title: de ? "CORE-PFAD" : "CORE PATH", rows: plan.corePath },
    { id: "counter" as const, title: de ? "ADAPTIVE KONTER" : "ADAPTIVE COUNTERS", rows: plan.adaptiveCounters },
    { id: "situational" as const, title: de ? "SITUATIV" : "SITUATIONAL", rows: plan.situational },
  ];
  const stages = [{ id: "early", label: de ? "FRÜH" : "EARLY", rows: plan.early }, { id: "mid", label: de ? "MITTEL" : "MID", rows: plan.mid }, { id: "late", label: de ? "SPÄT" : "LATE", rows: plan.late }];
  const activeStageIndex = stages.findIndex((phase) => phase.id === stage);
  const minute = Math.floor((match?.game_time_s ?? 0) / 60), second = String((match?.game_time_s ?? 0) % 60).padStart(2, "0");
  const evidenceMatches = buyTarget === "team" ? current?.teamMatches ?? 0 : current?.carryMatches ?? 0;
  const confidence = evidenceMatches >= 2000 ? (de ? "HOHE SICHERHEIT" : "HIGH CONFIDENCE") : evidenceMatches >= 250 ? (de ? "MITTEL" : "MEDIUM") : (de ? "BEGRENZT" : "LIMITED");
  const alternatives = recommendations.filter((entry) => !owned.has(entry.item.id) && entry.item.id !== current?.item.id).sort((a, b) => (plan.nextBuyOrder.find((row) => row.itemId === b.item.id)?.nextBuyScore ?? -Infinity) - (plan.nextBuyOrder.find((row) => row.itemId === a.item.id)?.nextBuyScore ?? -Infinity)).slice(0, 3);

  return <section className="desktop-build-page redesigned-build" aria-label="Build Lab">
    <header className="desktop-build-intro"><div><small>COUNTERLOCK / BUILD LAB</small><h1>{de ? "Kaufentscheidung" : "Build Lab"}</h1><p>{de ? "Dein nächster Kauf für dieses Match." : "Your next purchase for this match."}</p></div><span className={`desktop-live-indicator${live ? " active" : ""}`}>{live ? "● LIVE MATCH" : "○ WAITING FOR MATCH"}</span></header>
    <div className="desktop-build-layout">
      <div className="desktop-build-main">
        <section className="build-next" aria-labelledby="build-next-title">
          <div className="build-section-kicker"><span>{de ? "NEXT BUY" : "NEXT BUY"}</span><span>{live && match?.game_time_s != null ? `${stage.toUpperCase()} GAME · ${minute}:${second}` : live ? "LIVE" : "AWAITING MATCH"}</span></div>
          {current ? <>
            <div className="build-next-main"><div className="build-next-icon">{icon(current.item.id)}</div><div className="build-next-info"><small>{(current.item.item_slot_type ?? "ITEM").toUpperCase()}</small><h2 id="build-next-title">{current.item.name}</h2><div className="build-next-target">{targetPlayer ? <><b>VS</b> {targetProfile?.name || "Player"} · {heroes.get(targetPlayer.hero_id!)?.name ?? "Hero"}</> : de ? "GEGEN GEGNERTEAM" : "VS ENEMY TEAM"}</div></div><div className="build-next-price"><strong>◈ {currentCost?.toLocaleString(locale) ?? "—"}</strong><b className={purchase.status === "buy" ? "affordable" : ""}>{affordability}</b></div></div>
            <div className="build-why"><header><strong>{de ? "WARUM JETZT" : "WHY NOW"}</strong><small title={`${evidenceMatches.toLocaleString(locale)} relevant matches`}>{confidence}{evidenceMatches ? ` · ${evidenceMatches.toLocaleString(locale)} ${de ? "MATCHES" : "MATCHES"}` : ""}</small></header><ul><li>{targetPlayer ? `${de ? "Höchste aktuelle Gefahr" : "Top current threat"}: ${targetProfile?.name || "Player"} · ${heroes.get(targetPlayer.hero_id!)?.name ?? "Hero"}` : (de ? "Passt zum erkannten Gegnerteam" : "Fits the detected enemy team")}</li><li>{(current.counterUrgency ?? 0) >= .25 ? (de ? "Konterantwort auf aktuellen Druck" : "Counter response to current pressure") : (de ? "Starker Matchup-Beleg" : "Strong matchup evidence")}</li><li>{onCorePath ? (de ? "Auf deinem normalen Core-Pfad" : "On your normal core path") : `${de ? "Build-Abweichung" : "Build deviation"}: ${deviation < .035 ? (de ? "NIEDRIG" : "LOW") : deviation < .09 ? (de ? "MITTEL" : "MEDIUM") : (de ? "HOCH" : "HIGH")}`}</li></ul>
              {detailCurrent && <details className="build-details"><summary>{de ? "DETAILS UND MATCHUP-BELEG" : "DETAILS AND MATCHUP EVIDENCE"}</summary><div><span>{de ? "Helden-Fit" : "Hero fit"}<b>{detailCurrent.personalFit == null ? "—" : Math.round(detailCurrent.personalFit * 100)}</b></span><span>{de ? "Konter-Fit" : "Counter fit"}<b>{detailCurrent.counterUrgency == null ? "—" : Math.round(detailCurrent.counterUrgency * 100)}</b></span><span>{de ? "Kaufzeitpunkt" : "Buy timing"}<b>{Math.floor((buyTarget === "team" ? current.teamBuyTime : current.carryBuyTime) / 60)}m</b></span><span>{de ? "Persönlicher Fit" : "Personal fit"}<b>{detailCurrent.personalFit == null ? "—" : Math.round(detailCurrent.personalFit * 100)}</b></span><span>{de ? "Abweichungskosten" : "Deviation cost"}<b>{deviation.toFixed(2)}</b></span></div></details>}
            </div>
            {normalCore && <div className="build-core-adaptive"><div><small>{de ? "NORMALER CORE" : "NORMAL CORE"}</small><b>{normalCore.item.name}</b></div><span aria-hidden="true">→</span><div><small>{onCorePath ? (de ? "CORE-PFAD" : "ON CORE PATH") : (de ? "ADAPTIVER KAUF" : "ADAPTIVE BUY")}</small><b>{current.item.name}</b></div></div>}
          </> : <div className="desktop-build-await"><strong>{live ? (de ? "Keine passende Kaufempfehlung verfügbar" : "No matching buy recommendation yet") : (de ? "Build erscheint mit dem Match" : "Build appears with your match")}</strong><p>{live ? (de ? "Spieler und Gegner wurden erkannt, passende Kaufdaten fehlen noch." : "The player and enemies are detected; matching item evidence is not available yet.") : (de ? "Starte ein Match, um eine situative Kaufempfehlung zu sehen." : "Start a match to see a match-specific purchase recommendation.")}</p></div>}
        </section>

        <section className="build-inventory" aria-label={de ? "Aktuelles Inventar" : "Current inventory"}><header><strong>{de ? "AKTUELLES INVENTAR" : "CURRENT INVENTORY"}</strong><small>{live && advice?.inventory_known ? "LIVE" : de ? "MANUELL / UNBEKANNT" : "MANUAL / UNKNOWN"}</small></header>{(["weapon", "vitality", "spirit", "flex"] as const).map((category) => { const entries = category === "flex" ? flex : inventory[category]; return <div className="build-inventory-row" key={category}><small>{category === "weapon" ? (de ? "WAFFE" : "WEAPON") : category.toUpperCase()}</small><div>{[...entries, ...Array.from({ length: Math.max(0, 4 - entries.length) }, () => null)].slice(0, 4).map((item, index) => <span className={`build-inventory-slot${item ? " is-owned" : ""}`} key={item?.id ?? `empty-${category}-${index}`} title={item ? `${item.name} · ${liveOwned.has(item.id) ? "LIVE" : "MANUAL"} · ◈ ${item.cost?.toLocaleString(locale) ?? "—"}` : "Empty slot"} aria-label={item ? `${item.name}, owned ${liveOwned.has(item.id) ? "live" : "manually"}` : "Empty slot"}>{item ? <>{icon(item.id)}<b aria-hidden="true">✓</b></> : <i aria-hidden="true" />}</span>)}</div></div>; })}</section>

        {current && <section className="build-groups"><header><strong>{de ? "BUILD-OPTIONEN" : "BUILD OPTIONS"}</strong><div role="group" aria-label={de ? "Build-Pfad filtern" : "Filter build path"}>{groups.map((group) => <button key={group.id} aria-pressed={groupFilter === group.id} onClick={() => setGroupFilter(groupFilter === group.id ? "all" : group.id)}>{group.id === "counter" ? (de ? "KONTER" : "COUNTERS") : group.title}</button>)}</div></header><div className="build-groups-grid">{groups.filter((group) => groupFilter === "all" || groupFilter === group.id).map((group) => <section key={group.id}><small>{group.title}</small>{group.rows.slice(0, 4).map((entry) => { const covered = itemTargetIds(entry), target = covered.map((id) => enemies.find((enemy) => enemy.hero_id === id)).find(Boolean), profile = target?.account_id == null ? undefined : profiles[target.account_id]; const dimmed = selectedEnemy != null && !covered.includes(selectedEnemy); const coverage = covered.map((id) => heroes.get(id)?.name).filter(Boolean).slice(0, 3).join(", "); return <div className={`build-group-item${dimmed ? " is-dimmed" : ""}${owned.has(entry.item.id) ? " is-owned" : ""}`} key={entry.item.id}><span className="build-group-icon">{icon(entry.item.id)}{owned.has(entry.item.id) && <b>✓</b>}</span><span><strong>{entry.item.name}</strong><small>{group.id === "counter" && covered.length ? `Covers ${coverage || profile?.name || "enemy"}` : `${entry.item.item_slot_type ?? "Item"} · ${entry.item.item_tier ? `T${entry.item.item_tier}` : "Core path"}`}</small></span>{covered.length > 1 && <em>{covered.length} {de ? "ZIELE" : "TARGETS"}</em>}</div>; })}{!group.rows.length && <p>{de ? "Keine Items" : "No items"}</p>}{group.rows.length > 4 && <small className="build-more">+{group.rows.length - 4} {de ? "WEITERE IM KAUFPFAD" : "MORE IN PURCHASE PATH"}</small>}</section>)}</div></section>}

        {current && alternatives.length > 0 && <details className="build-alternatives"><summary>{de ? "WEITERE KÄUFE ANSEHEN" : "VIEW ALTERNATIVE BUYS"}</summary>{alternatives.map((entry) => <div key={entry.item.id}><span>{icon(entry.item.id)}</span><strong>{entry.item.name}</strong><small>{entry.item.id === plan.normalCoreNextId ? (de ? "Normaler Core-Kauf" : "Normal core buy") : (de ? "Alternative Empfehlung" : "Alternative recommendation")}</small><b>◈ {entry.item.cost?.toLocaleString(locale) ?? "—"}</b></div>)}</details>}

        <section className="desktop-full-build build-path"><header className="desktop-full-build-head"><div><small>{de ? "KAUFPFAD" : "PURCHASE PATH"}</small><h2>{de ? "Dein normaler Core und Match-Konter" : "Core path and match counters"}</h2><p>{de ? "Owned-Status und adaptive Käufe im Zeitverlauf." : "Owned state and adaptive buys in order."}</p></div><div className="desktop-build-presets"><button type="button" onClick={onSave}>{de ? "BUILD SPEICHERN" : "SAVE BUILD"}</button><button type="button" onClick={onLoad}>{de ? "BUILD LADEN" : "LOAD BUILD"}</button>{presetMessage && <small>{presetMessage}</small>}</div></header><div className="build-path-meta"><span>{de ? "GESAMT" : "TOTAL"} ◈ {cost.toLocaleString(locale)}</span><span>{de ? "NOCH OFFEN" : "REMAINING"} ◈ {remainingCost.toLocaleString(locale)}</span><span>{plan.purchaseOrder.length}/16 {de ? "ITEMS" : "ITEMS"}</span></div><div className="desktop-purchase-stages">{stages.map((phase, index) => <section className={`desktop-purchase-stage ${phase.id}${stage === phase.id ? " is-active" : index < activeStageIndex ? " is-past" : " is-future"}`} key={phase.id}><header><span>0{index + 1}</span><strong>{phase.label}</strong><small>{stage === phase.id ? (de ? "AKTUELL" : "CURRENT") : `${phase.rows.length} ITEMS`}</small></header><div>{phase.rows.map((entry) => { const order = plan.purchaseOrder.findIndex((row) => row.item.id === entry.item.id) + 1, isOwned = owned.has(entry.item.id), isCurrent = entry.item.id === current?.item.id, role = isOwned ? "OWNED" : isCurrent ? "NEXT" : plan.adaptiveCounters.some((row) => row.item.id === entry.item.id) ? "COUNTER" : plan.situational.some((row) => row.item.id === entry.item.id) ? "SITUATIONAL" : "CORE"; const targets = itemTargetIds(entry), targetHero = targets.map((id) => heroes.get(id)).find(Boolean); const selectedMatch = selectedEnemy == null || targets.includes(selectedEnemy); return <article className={`${isOwned ? "owned" : ""}${isCurrent ? " next" : ""}${!selectedMatch ? " is-dimmed" : ""}`} key={entry.item.id}><button type="button" onClick={() => onToggleOwned(entry.item.id)} aria-pressed={isOwned} disabled={liveOwned.has(entry.item.id)} title={liveOwned.has(entry.item.id) ? (de ? "Live erkanntes Item" : "Detected live item") : (de ? "Besitzstatus umschalten" : "Toggle owned state")}><b>{String(order).padStart(2, "0")}</b><span className="desktop-purchase-icon">{icon(entry.item.id)}</span><span className="desktop-purchase-copy"><strong>{entry.item.name}</strong><small>{entry.item.item_slot_type ?? "ITEM"} · T{entry.item.item_tier ?? "—"}</small></span><span className="desktop-purchase-cost">{isOwned ? "✓" : `◈ ${(entry.item.cost ?? 0).toLocaleString(locale)}`}</span></button><small className={`desktop-purchase-target role-${role.toLowerCase()}`}><b>{role}</b>{targetHero && <span>{de ? "GEGEN" : "VS"} {targetHero.name}</span>}</small></article>; })}</div></section>)}</div>
          {plan.sellSuggestions.length > 0 && <section className="desktop-sell-plan"><header><small>↻</small><div><strong>{de ? "VERKAUFEN / ERSETZEN" : "SELL / REPLACE"}</strong><span>{de ? "Nur bei echtem Upgrade" : "Only when an upgrade is recommended"}</span></div></header>{plan.sellSuggestions.map(({ sell, replacement, reason }) => <div className="desktop-sell-pair" key={`${sell.item.id}-${replacement.item.id}`}><span>{sell.item.name}</span><b>→</b><strong>{replacement.item.name}</strong><small>{reason === "upgrade_obsolete" ? (de ? "Upgrade macht den Slot frei" : "Upgrade replaces component") : (de ? "Höherer Matchwert" : "Higher match value")}</small></div>)}</section>}
        </section>
      </div>

      <aside className="desktop-build-context build-sidebar"><details className="build-sidebar-collapse"><summary>{de ? "MATCH-KONTEXT ANZEIGEN" : "SHOW MATCH CONTEXT"}</summary><div><small>{de ? "DU" : "YOU"}</small><h2>{ownProfile?.name || "Player"}</h2><p>{own?.hero_id != null ? heroes.get(own.hero_id)?.name ?? `Hero #${own.hero_id}` : de ? "Held nicht erkannt" : "Hero unavailable"} · {playerRank(ownProfile?.estimatedRankNumber)?.label ?? "Rank —"}</p>{souls != null && <b className="build-sidebar-souls">◈ {souls.toLocaleString(locale)} {de ? "SEELEN" : "SOULS"}</b>}<div className="desktop-build-context-rule"/><small>{de ? "TOP-GEFAHREN" : "TOP THREATS"}</small>{rankedThreats.length ? <ol className="desktop-threat-list">{rankedThreats.slice(0, 6).map((threat, index) => { const player = enemies.find((enemy) => enemy.hero_id === threat.heroId), profile = player?.account_id == null ? undefined : profiles[player.account_id], selected = selectedEnemy === threat.heroId, targets = current ? itemTargetIds(current) : []; return <li key={threat.heroId} className={selected ? "selected" : ""}><button type="button" aria-pressed={selected} onClick={() => setSelectedEnemy(selected ? null : threat.heroId)}><span>#{index + 1} {profile?.name || "Player"}</span><small>{heroes.get(threat.heroId)?.name ?? `Hero #${threat.heroId}`} · {playerRank(profile?.estimatedRankNumber)?.label ?? "Rank —"} · {player?.net_worth?.toLocaleString(locale) ?? "—"} NW</small>{targets.includes(threat.heroId) && <b>{de ? "GEGEN KAUF" : "COUNTER TARGET"}</b>}</button></li>; })}</ol> : <p>{de ? "Keine Gegner erkannt" : "No enemies detected"}</p>}{selectedEnemy != null && <button className="build-clear-filter" type="button" onClick={() => setSelectedEnemy(null)}>{de ? "GEFAHRENFILTER LÖSCHEN" : "CLEAR THREAT FILTER"}</button>}<div className="desktop-build-context-rule"/><p className="desktop-build-source">{de ? "NW ist Gesamtvermögen, kein Shop-Guthaben. Gegneritems sind nicht live verfügbar." : "NW is net worth, not shop balance. Enemy inventory is not available live."}</p></div></details></aside>
    </div>
  </section>;
}
