import { useState } from "react";
import type { RecommendationOutcome } from "../../lib/data/recommendation-outcomes.ts";
import { recommendationDecisions, reviewTimeline, threatEvolution } from "../../lib/match-history";

type Props = { match: RecommendationOutcome; heroNames: Map<number, string>; itemNames: Map<number, string>; itemCategories?: Map<number, string>; heroImages?: Map<number, string>; itemImages?: Map<number, string>; onBack: () => void };
const clock = (value: number) => `${String(Math.floor(value / 60)).padStart(2, "0")}:${String(Math.floor(value % 60)).padStart(2, "0")}`;
const number = (value: number | null, digits = 0) => value == null ? "—" : value.toLocaleString(undefined, { maximumFractionDigits: digits });

export function MatchReview({ match, heroNames, itemNames, itemCategories, heroImages, itemImages, onBack }: Props) {
  const [selectedEvent, setSelectedEvent] = useState<number | null>(null);
  const purchases = [...new Map(match.actualPurchases.filter((p) => p.itemId > 0 && p.gameTime >= 0).sort((a, b) => a.gameTime - b.gameTime).map((p) => [`${p.itemId}:${p.gameTime}`, p])).values()];
  const decisions = recommendationDecisions(match);
  const buildGroups = ["weapon", "vitality", "spirit", "flex"].map((category) => ({ category, items: purchases.filter((p) => (itemCategories?.get(p.itemId)?.toLowerCase() ?? "flex") === category).slice(-6) })).filter((group) => group.items.length);
  const counts = Object.fromEntries(["FOLLOWED", "DELAYED", "SKIPPED", "UNKNOWN"].map((state) => [state, decisions.filter((d) => d.state === state).length]));
  const timeline = reviewTimeline(match);
  const threatSnapshots = threatEvolution(match);
  const date = match.date ? new Date(match.date * 1000).toLocaleString(undefined, { dateStyle: "medium", timeStyle: "short" }) : "Date unavailable";
  const hero = heroNames.get(match.heroId) ?? `Hero #${match.heroId}`;
  return <>
    <header className="match-history-header review-page-head"><small>COUNTERLOCK / MATCH REVIEW</small><button className="review-back" onClick={onBack}>← My matches</button><time>{date}</time></header>
    <div className={`review-result ${match.result}`}>
      <div className="review-result-main"><span className="review-result-label">{match.result.toUpperCase()}</span><h1>{hero}</h1><p>{match.durationSeconds != null ? clock(match.durationSeconds) : "Duration unavailable"}<span> · </span>Match {match.matchId}</p></div>
      <div className="review-player">{heroImages?.get(match.heroId) ? <img className="review-avatar" src={heroImages.get(match.heroId)} alt={`${hero} portrait`} /> : <span className="review-avatar" aria-hidden="true">{hero.slice(0, 1).toUpperCase()}</span>}<div><strong>{match.rankSnapshot?.playerName??"Local player"}</strong><small>{match.rankSnapshot?`${match.rankSnapshot.estimatedRankNumber==null?"Rank —":`Rank ${match.rankSnapshot.estimatedRankNumber}`}${match.rankSnapshot.ppScore==null?"":` · PP ${match.rankSnapshot.ppScore}`}`:"Rank unavailable"}</small></div></div>
    </div>
    <div className="review-metrics" aria-label="Match summary">
      <Metric label="K / D / A" value={match.performance.kills != null && match.performance.deaths != null && match.performance.assists != null ? `${match.performance.kills} / ${match.performance.deaths} / ${match.performance.assists}` : "—"} detail={match.performance.kda == null ? "Unavailable in saved match data" : `KDA ratio ${number(match.performance.kda, 2)}`} />
      <Metric label="SOULS / MIN" value={number(match.performance.spm)} />
      <Metric label="FINAL NET WORTH" value={number(match.netWorth)} />
      <Metric label="DAMAGE / MIN" value={number(match.performance.damagePerMinute)} />
      {match.performance.mvpScore != null && <Metric label="MVP SCORE" value={number(match.performance.mvpScore, 2)} />}
    </div>
    <div className="review-report-grid">
      <section className="review-section build-overview"><SectionHeading eyebrow="MATCH RECORD" title="Build overview" /><div className="review-build-columns"><div><h3>ACTUAL FINAL BUILD</h3><p className="review-muted">{match.purchaseHistoryAvailable === false ? "Purchase timeline is not included in public match history." : "Purchase order captured locally when available."}</p>{purchases.length ? buildGroups.map((group) => <div className="review-build-group" key={group.category}><small>{group.category.toUpperCase()}</small><div className="review-item-list">{group.items.map((p) => <span key={`${p.itemId}-${p.gameTime}`} title={`${itemNames.get(p.itemId) ?? `Item #${p.itemId}`} · ${clock(p.gameTime)}`}>{itemImages?.get(p.itemId) ? <img src={itemImages.get(p.itemId)} alt="" /> : <b className="review-item-placeholder">{(itemNames.get(p.itemId) ?? `#${p.itemId}`).slice(0, 2)}</b>}<small>{itemNames.get(p.itemId) ?? `#${p.itemId}`} · {clock(p.gameTime)}</small></span>)}</div></div>) : <p>{match.purchaseHistoryAvailable === false ? "Purchase data unavailable for this match." : "No purchases recorded."}</p>}</div><div><h3>RECOMMENDED PATH</h3><p className="review-muted">Important local recommendation snapshots</p><div className="review-path-list">{decisions.length ? decisions.slice(0, 6).map((d, i) => <div key={`${d.gameTime}-${d.recommendedItemId}-${i}`}><time>{clock(d.gameTime)}</time><strong>{itemNames.get(d.recommendedItemId) ?? `Item #${d.recommendedItemId}`}</strong><span>{d.state}</span></div>) : <p>No recommendation timeline was saved.</p>}</div></div></div><div className="review-decision-counts"><span><b>{counts.FOLLOWED}</b> followed</span><span><b>{counts.DELAYED}</b> delayed</span><span><b>{counts.SKIPPED}</b> skipped</span><span><b>{counts.UNKNOWN}</b> unknown</span></div></section>
      <section className="review-section recommendation-review"><SectionHeading eyebrow="DECISIONS" title="Recommendation review" />{decisions.length ? decisions.slice(0, 8).map((d, i) => <article className="review-decision" key={`${d.gameTime}-${d.recommendedItemId}-${i}`}><time>{clock(d.gameTime)}</time><div><strong>{itemNames.get(d.recommendedItemId) ?? `Item #${d.recommendedItemId}`}</strong><small>Recommended · score {number(d.score, 2)}</small>{d.reasonCodes?.length ? <span className="review-reason-codes">{d.reasonCodes.map(reasonLabel).join(" · ")}</span> : null}{d.normalCoreItemId && d.normalCoreItemId!==d.recommendedItemId ? <span className="review-reason-codes">Core path: {itemNames.get(d.normalCoreItemId)??`Item #${d.normalCoreItemId}`}</span> : null}</div><span className={`decision-state ${d.state.toLowerCase()}`}>{d.state}{d.delay != null ? ` · +${clock(d.delay)}` : ""}</span>{d.bought && <small className="review-bought">Bought {clock(d.bought.gameTime)}</small>}</article>) : <p className="review-empty">No local recommendations were captured during this match.</p>}</section>
      <section className="review-section timeline-section"><SectionHeading eyebrow="MATCH FLOW" title="Timeline" />{timeline.length ? <ol className="review-timeline">{timeline.map((event, i) => <li key={`${event.time}-${event.kind}-${event.id}-${i}`} className={`${event.kind} ${selectedEvent === event.id ? "related" : ""}`}><time>{clock(event.time)}</time><i aria-hidden="true">{event.kind === "purchase" ? "＋" : event.kind === "threat" ? "!" : "◇"}</i><button type="button" aria-pressed={selectedEvent === event.id} onClick={() => setSelectedEvent(selectedEvent === event.id ? null : event.id)}><strong>{event.kind==="threat"?heroNames.get(event.id)??`Hero #${event.id}`:itemNames.get(event.id) ?? `Item #${event.id}`}</strong><small>{event.kind === "purchase" ? "Purchased" : event.kind === "threat" ? "Became the primary live threat" : "Recommended"}</small></button></li>)}</ol> : <p className="review-empty">No timeline events were saved for this match.</p>}{selectedEvent != null && <p className="review-event-link">Related recorded events for {itemNames.get(selectedEvent) ?? heroNames.get(selectedEvent) ?? `#${selectedEvent}`} are highlighted.</p>}<p className="review-note">Recorded events describe timing; they do not establish that a purchase caused the match result.</p></section>
      <section className="review-section threat-section"><SectionHeading eyebrow="LIVE SNAPSHOTS" title="Threat evolution" />{threatSnapshots.length ? <ol className="threat-evolution-list">{threatSnapshots.map(snapshot=><li key={`${snapshot.time}-${snapshot.threats[0]?.heroId}`}><time>{clock(snapshot.time)}</time><span>{snapshot.threats.map((threat,index)=><b key={threat.heroId}>{index===0?"PRIMARY · ":""}{heroNames.get(threat.heroId)??`Hero #${threat.heroId}`} <small>{Math.round(threat.weight*100)}% relative weight</small></b>)}</span></li>)}</ol>:<p className="review-empty">Threat snapshots weren’t recorded for this match.</p>}<div className="review-unknown-profile"><strong>Team pressure scores</strong><span>Not retained in this match record</span></div></section>
      <aside className="review-context"><SectionHeading eyebrow="PERSONAL CONTEXT" title={`Your ${hero} history`} /><p>Recent tendencies are available as local match records are collected.</p><div className="review-context-row"><span>This match</span><strong>{purchases.length} purchases recorded</strong></div><div className="review-context-row"><span>Other context</span><strong>Not enough saved data</strong></div><small>Personal history is descriptive and does not predict future results.</small></aside>
      <section className="review-section data-section"><SectionHeading eyebrow="SOURCE" title="Match data" /><dl><div><dt>Player identity</dt><dd>{match.rankSnapshot?.playerName??"Local player"} · account linked</dd></div><div><dt>Rank snapshot</dt><dd>{match.rankSnapshot?.estimatedRankNumber==null?"Unavailable":`Rank ${match.rankSnapshot.estimatedRankNumber}${match.rankSnapshot.ppScore==null?"":` · PP ${match.rankSnapshot.ppScore}`}`}</dd></div><div><dt>Queue</dt><dd>{match.matchMode??"Unavailable"}</dd></div><div><dt>Timeline source</dt><dd>{match.purchaseHistoryAvailable===false?"Deadlock API history · no purchase timeline":"Local recommendation and purchase records"}</dd></div></dl></section>
    </div>
  </>;
}
function Metric({ label, value, detail }: { label: string; value: string; detail?: string }) { return <article><small>{label}</small><b>{value}</b>{detail && <span>{detail}</span>}</article>; }
function SectionHeading({ eyebrow, title }: { eyebrow: string; title: string }) { return <header className="review-section-heading"><small>{eyebrow}</small><h2>{title}</h2></header>; }
function reasonLabel(code:string){return ({lane_matchup:"Lane matchup",core_path:"Core path",counter_mechanics:"Mechanic counter",multi_enemy_coverage:"Multi-enemy coverage",low_build_deviation:"Low build deviation"} as Record<string,string>)[code]??code;}
