import { useMemo, useState, type FormEvent } from "react";
import type { RecommendationOutcome } from "../../lib/data/recommendation-outcomes.ts";
import { steamAccountId } from "../../lib/steam-account-id";
import type { SteamHistoryProfile } from "../../MatchHistory";

type PendingMatch = { matchId: number; heroId: number; recommendations: Array<{ gameTime: number; recommendedItemId: number; score: number }>; matchMode?: string | null; rankSnapshot?: RecommendationOutcome["rankSnapshot"] };
type Props = { outcomes: RecommendationOutcome[]; pendingMatches: PendingMatch[]; heroNames: Map<number, string>; itemNames: Map<number, string>; heroImages?: Map<number, string>; itemImages?: Map<number, string>; historyStatus?: "loading" | "connected" | "local" | "unavailable" | "not_configured"; accountId?: number | null; playerName?: string | null; onLinkSteamProfile?: (profile: SteamHistoryProfile) => void; onForgetSteamProfile?: () => void; onSelect: (id: number) => void };
export function MatchLibrary({ outcomes, pendingMatches, heroNames, itemNames, heroImages, itemImages, historyStatus = "not_configured", accountId, playerName, onLinkSteamProfile, onForgetSteamProfile, onSelect }: Props) {
  const [hero, setHero] = useState("all"), [result, setResult] = useState("all"), [period, setPeriod] = useState("all"), [dateReference,setDateReference]=useState<number|null>(null), [queue,setQueue]=useState("all");
  const [steamQuery, setSteamQuery] = useState(""), [steamBusy, setSteamBusy] = useState(false), [steamError, setSteamError] = useState(""), [steamCandidates, setSteamCandidates] = useState<SteamHistoryProfile[]>([]);
  const rows = useMemo(() => outcomes.filter((m) => (hero === "all" || String(m.heroId) === hero) && (result === "all" || m.result === result) && (period === "all" || (dateReference != null && m.date != null && m.date >= dateReference - Number(period) * 86400)) && (queue === "all" || rankedQueue(m.matchMode)===(queue==="ranked"))), [outcomes, hero, result, period, dateReference,queue]);
  const pendingRows = pendingMatches.filter((m) => (hero === "all" || String(m.heroId) === hero) && result === "all" && period === "all" && (queue==="all"||rankedQueue(m.matchMode)===(queue==="ranked")) && !outcomes.some((done) => done.matchId === m.matchId)).sort((a, b) => b.matchId - a.matchId);
  const heroCounts = useMemo(() => [...new Set(outcomes.map((m) => m.heroId))].map((id) => ({ id, count: outcomes.filter((m) => m.heroId === id).length })).sort((a, b) => b.count - a.count), [outcomes]);
  const heroMatches = hero === "all" ? [] : outcomes.filter((m) => String(m.heroId) === hero);
  const itemFrequency = new Map<number, number>();
  heroMatches.forEach((match) => new Set(match.actualPurchases.map((item) => item.itemId)).forEach((id) => itemFrequency.set(id, (itemFrequency.get(id) ?? 0) + 1)));
  const commonItems = [...itemFrequency].sort((a, b) => b[1] - a[1]).slice(0, 5);
  async function findSteamProfile(event: FormEvent<HTMLFormElement>) {
    event.preventDefault(); const query = steamQuery.trim(); if (!query || !onLinkSteamProfile) return;
    setSteamBusy(true); setSteamError(""); setSteamCandidates([]);
    try {
      const directId = steamAccountId(query);
      let profiles: SteamHistoryProfile[];
      if (directId != null) {
        const response = await fetch(`https://api.deadlock-api.com/v1/players/steam?account_ids=${directId}`);
        const rows: unknown = response.ok ? await response.json() : [];
        profiles = Array.isArray(rows) ? rows.flatMap((entry) => steamProfile(entry, directId)) : [];
        if (!profiles.length) profiles = [{ account_id: directId, personaname: `Steam ${directId}`, profileurl: "", avatar: "" }];
      } else {
        const params = new URLSearchParams({ search_query: query, limit: "5", min_matches_played_last_30d: "0" });
        const response = await fetch(`https://api.deadlock-api.com/v1/players/steam-search?${params}`);
        if (!response.ok) throw new Error("Steam profile search failed");
        const rows: unknown = await response.json();
        profiles = Array.isArray(rows) ? rows.flatMap((entry) => steamProfile(entry)) : [];
      }
      const exact = profiles.find((profile) => profile.personaname.toLowerCase() === query.toLowerCase());
      if (exact || profiles.length === 1) onLinkSteamProfile(exact ?? profiles[0]);
      else if (profiles.length) setSteamCandidates(profiles);
      else setSteamError("No matching public Steam profile. Try your numeric Steam account ID.");
    } catch { setSteamError("Steam profile lookup failed. Try a numeric Steam account ID."); }
    finally { setSteamBusy(false); }
  }
  return <>
    <header className="match-history-header"><small>COUNTERLOCK / PERSONAL RECORD</small><h1>My matches</h1><p>Deadlock match history from the API, combined with Counterlock’s saved recommendations and purchases.</p><span className={`history-source ${historyStatus}`}><i />{historyStatus === "loading" ? "SYNCING MATCH HISTORY" : historyStatus === "connected" ? outcomes.length || pendingMatches.length ? "DEADLOCK API HISTORY" : "API CONNECTED · NO MATCHES FOUND" : historyStatus === "unavailable" ? outcomes.length || pendingMatches.length ? "API UNAVAILABLE · LOCAL RECORDS" : "API UNAVAILABLE" : accountId ? "LOCAL RECORDS · API NOT READY" : "LINK STEAM FOR API HISTORY"}</span></header>
    {initialLinkNeeded(accountId, onLinkSteamProfile) && <section className="history-steam-link"><div><strong>Load your Deadlock match history</strong><p>Link a public Steam profile so Counterlock can look up your account’s history. No Steam password is requested.</p></div><form onSubmit={findSteamProfile}><label htmlFor="history-steam-query">STEAM NAME OR ACCOUNT ID</label><div><input id="history-steam-query" value={steamQuery} onChange={(event) => setSteamQuery(event.target.value)} placeholder="Profile name, SteamID3, or SteamID64" autoComplete="off" /><button type="submit" disabled={steamBusy || !steamQuery.trim()}>{steamBusy ? "SEARCHING…" : "FIND PROFILE"}</button></div></form>{steamCandidates.length > 0 && <div className="history-steam-candidates">{steamCandidates.map((profile) => <button key={profile.account_id} type="button" onClick={() => onLinkSteamProfile?.(profile)}><span>{profile.avatar && <img src={profile.avatar} alt="" />}{profile.personaname}</span><small>ACCOUNT {profile.account_id}</small></button>)}</div>}{steamError && <small className="history-steam-error" role="status">{steamError}</small>}</section>}
    {accountId && playerName && onForgetSteamProfile && <div className="history-linked-profile"><span>STEAM PROFILE · {playerName} · {accountId}</span><button type="button" onClick={onForgetSteamProfile}>UNLINK</button></div>}
    <div className="history-library-summary"><div><strong>{rows.length}</strong><span>matches</span></div><div><strong>{rows.filter((match) => match.result === "win").length}</strong><span>wins</span></div><div><strong>{heroCounts.length}</strong><span>heroes played</span></div><div><strong>{pendingRows.length}</strong><span>pending reviews</span></div></div>
    {heroCounts.length > 0 && <section className="hero-summary-section"><header><small>PERSONAL HISTORY</small><h2>Most played</h2></header><div className="hero-summary-list">{heroCounts.slice(0, 5).map((entry) => <button key={entry.id} onClick={() => setHero(String(entry.id))} className={hero === String(entry.id) ? "selected" : ""}><span className="hero-summary-avatar" aria-hidden="true">{(heroNames.get(entry.id) ?? "?").slice(0, 1)}</span><strong>{heroNames.get(entry.id) ?? `Hero #${entry.id}`}</strong><small>{entry.count} {entry.count === 1 ? "match" : "matches"}</small></button>)}</div></section>}
    {hero !== "all" && <section className="personal-hero-history"><header><small>HERO HISTORY</small><h2>{heroNames.get(Number(hero)) ?? `Hero #${hero}`}</h2><span>{heroMatches.length} recorded {heroMatches.length === 1 ? "match" : "matches"}</span></header><div className="personal-hero-metrics"><div><small>DESCRIPTIVE WIN RATE</small><strong>{heroMatches.length ? `${Math.round(heroMatches.filter((m) => m.result === "win").length / heroMatches.length * 100)}%` : "—"}</strong></div><div><small>AVERAGE SPM</small><strong>{average(heroMatches.map((m) => m.performance.spm))}</strong></div><div><small>AVERAGE DURATION</small><strong>{average(heroMatches.map((m) => m.durationSeconds), true)}</strong></div><div><small>AVERAGE KDA RATIO</small><strong>{average(heroMatches.map((m) => m.performance.kda), false)}</strong></div></div><div className="personal-item-tendencies"><small>COMMON PERSONAL ITEMS · RECORDED IN MATCHES</small>{commonItems.length ? commonItems.map(([id, count]) => <span key={id}>{itemNames.get(id) ?? `Item #${id}`} <b>{count}/{heroMatches.length}</b></span>) : <p>Item history unavailable.</p>}</div></section>}
    <div className="history-controls" aria-label="Match filters"><label>HERO<select value={hero} onChange={(e) => setHero(e.target.value)}><option value="all">All heroes</option>{heroCounts.map(({ id }) => <option key={id} value={id}>{heroNames.get(id) ?? `Hero #${id}`}</option>)}</select></label><label>RESULT<select value={result} onChange={(e) => setResult(e.target.value)}><option value="all">All results</option><option value="win">Wins</option><option value="loss">Losses</option></select></label><label>DATE<select value={period} onChange={(e) => {const value=e.target.value;setPeriod(value);setDateReference(value==="all"?null:Date.now()/1000);}}><option value="all">All dates</option><option value="30">Last 30 days</option><option value="90">Last 90 days</option></select></label><label>QUEUE<select value={queue} onChange={e=>setQueue(e.target.value)}><option value="all">All queues</option><option value="ranked">Ranked</option><option value="unranked">Unranked</option></select></label></div>
    <div className="history-list" aria-label="Recorded matches">{rows.map((m) => <button className="history-match-row" key={m.matchId} onClick={() => onSelect(m.matchId)} aria-label={`Open ${m.result} ${heroNames.get(m.heroId) ?? `Hero ${m.heroId}`} match review`}>
      {heroImages?.get(m.heroId) ? <img className="history-hero-avatar" src={heroImages.get(m.heroId)} alt={`${heroNames.get(m.heroId) ?? "Hero"} portrait`} /> : <span className="history-hero-avatar" aria-hidden="true">{(heroNames.get(m.heroId) ?? "?").slice(0, 1)}</span>}<div className="history-match-main"><strong>{heroNames.get(m.heroId) ?? `Hero #${m.heroId}`}</strong><small>{rankLabel(m.rankSnapshot)} · {m.durationSeconds != null ? clock(m.durationSeconds) : "Duration —"}</small></div><span className={`history-result ${m.result}`}>{m.result.toUpperCase()}</span><div className="history-kda"><small>KDA</small><b>{m.performance.kda?.toFixed(2) ?? "—"}</b></div><div className="history-items" aria-label="Recorded purchases">{m.actualPurchases.slice(-6).map((item, i) => <span key={`${item.itemId}-${item.gameTime}-${i}`} title={itemNames.get(item.itemId) ?? `Item #${item.itemId}`}>{itemImages?.get(item.itemId) ? <img src={itemImages.get(item.itemId)} alt="" /> : (itemNames.get(item.itemId) ?? `#${item.itemId}`).slice(0, 2)}</span>)}</div><div className="history-match-meta"><strong>{m.matchMode??"Queue unknown"} · {m.recommendations.length} recommendations</strong><time>{m.date ? new Date(m.date * 1000).toLocaleString(undefined, { dateStyle: "medium", timeStyle: "short" }) : `Match ${m.matchId}`}</time></div><span className="history-open" aria-hidden="true">→</span>
    </button>)}{pendingRows.map((m) => <div className="history-match-row pending-match-row" key={`pending-${m.matchId}`} aria-label="Match analysis pending"><span className="history-hero-avatar" aria-hidden="true">{(heroNames.get(m.heroId) ?? "?").slice(0, 1)}</span><div className="history-match-main"><strong>{heroNames.get(m.heroId) ?? `Hero #${m.heroId}`}</strong><small>Match {m.matchId} · Post-match data pending</small></div><span className="pending-status">PENDING</span><div className="history-match-meta"><strong>{m.recommendations.length} recommendations captured</strong><time>Awaiting final match details</time></div></div>)}{!rows.length && !pendingRows.length && <div className="history-empty"><strong>{outcomes.length ? "No matches for these filters." : accountId ? "No matches returned for this Steam account." : "Connect Steam to load your match history."}</strong><p>{outcomes.length ? "Adjust the hero, result, or date filters." : accountId ? "The Deadlock API has no indexed history for this account yet. Counterlock’s locally saved records will appear here too." : "Link your public profile above. Counterlock will request match history directly from the Deadlock API."}</p></div>}</div>
  </>;
}
function initialLinkNeeded(accountId: number | null | undefined, onLink: Props["onLinkSteamProfile"]) { return accountId == null && Boolean(onLink); }
function steamProfile(value: unknown, fallbackId?: number): SteamHistoryProfile[] { if (!value || typeof value !== "object") return []; const row = value as Record<string, unknown>, accountId = Number.isInteger(row.account_id) ? row.account_id as number : fallbackId; if (!accountId) return []; return [{ account_id: accountId, personaname: typeof row.personaname === "string" && row.personaname ? row.personaname : `Steam ${accountId}`, profileurl: typeof row.profileurl === "string" ? row.profileurl : "", avatar: typeof row.avatarfull === "string" ? row.avatarfull : typeof row.avatar === "string" ? row.avatar : "" }]; }
function clock(seconds: number) { return `${Math.floor(seconds / 60)}:${String(seconds % 60).padStart(2, "0")}`; }
function rankedQueue(mode:string|null|undefined):boolean|null { if(!mode)return null;const value=mode.toLowerCase();if(value.includes("unranked")||value.includes("normal"))return false;if(value.includes("ranked"))return true;return null; }
function rankLabel(rank:RecommendationOutcome["rankSnapshot"]){if(!rank)return "Rank unavailable";const value=rank.estimatedRankNumber==null?"Rank unavailable":`Rank ${rank.estimatedRankNumber}`;return rank.ppScore==null?value:`${value} · PP ${rank.ppScore}`;}
function average(values: Array<number | null>, duration = false) { const known = values.filter((v): v is number => v != null && Number.isFinite(v)); if (!known.length) return "—"; const value = known.reduce((a, b) => a + b, 0) / known.length; return duration ? clock(value) : Math.round(value).toLocaleString(); }
